# Generated by Django 5.0.6 on 2024-08-10 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('talla', models.CharField(max_length=10)),
                ('marca', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_compra', models.DateField()),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Separado', 'Separado'), ('Vendido', 'Vendido')], default='Disponible', max_length=10)),
                ('categoria', models.CharField(choices=[('Zapatilla', 'Zapatilla'), ('Polo', 'Polo'), ('Mochila', 'Mochila')], max_length=20)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
