# Generated by Django 5.0.6 on 2024-08-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('COMPLETADO', 'Completado'), ('PENDIENTE', 'Pendiente')], default='COMPLETADO', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='tipo_venta',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('FRACCIONADO', 'Fraccionado'), ('DROPSHIPPING', 'Dropshipping')], default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
