# Generated by Django 5.0.6 on 2024-08-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_venta_estado_venta_tipo_venta_venta_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='total',
            new_name='pago_fraccionado',
        ),
        migrations.AddField(
            model_name='venta',
            name='total_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
