# Generated by Django 5.0.6 on 2024-08-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_total_venta_pago_fraccionado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8)),
                ('imagen_dni1', models.ImageField(blank=True, null=True, upload_to='dni_images/')),
                ('imagen_dni2', models.ImageField(blank=True, null=True, upload_to='dni_images/')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=15)),
            ],
        ),
    ]
