# Generated by Django 5.0.6 on 2024-08-12 02:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_capital_monto_inicial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capital',
            old_name='monto_inicial',
            new_name='monto',
        ),
        migrations.RemoveField(
            model_name='capital',
            name='fecha_creacion',
        ),
        migrations.AlterField(
            model_name='historialcapital',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
