# Generated by Django 4.2.4 on 2024-08-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_rename_monto_inicial_capital_monto_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venta",
            name="fecha_compra",
            field=models.DateTimeField(),
        ),
    ]
