# Generated by Django 4.2.4 on 2024-08-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_alter_venta_fecha_compra"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gasto",
            name="tipo_gasto",
            field=models.CharField(
                choices=[
                    ("Pasaje", "Pasaje"),
                    ("Comida", "Comida"),
                    ("Otros", "Otros"),
                ],
                max_length=50,
            ),
        ),
    ]
