# Generated by Django 4.2.4 on 2024-08-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_alter_gasto_tipo_gasto"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="eliminado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="emisor",
            name="eliminado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gasto",
            name="eliminado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="producto",
            name="eliminado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="venta",
            name="eliminado",
            field=models.BooleanField(default=False),
        ),
    ]
