# Generated by Django 4.2.4 on 2024-08-24 08:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0013_cliente_eliminado_emisor_eliminado_gasto_eliminado_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PagoFraccionado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto_pagado", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha_pago", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "ganancia",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos",
                        to="myapp.venta",
                    ),
                ),
            ],
        ),
    ]
